src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $show_home;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getShowHome(): ?bool
    {
        return $this->show_home;
    }

    public function setShowHome(bool $show_home): self
    {
        $this->show_home = $show_home;

        return $this;
    }
}

src/Form/BlogType.php
<?php

namespace App\Form;

use App\Entity\Blog;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BlogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('image')
            ->add('date')
            ->add('show_home')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Blog::class,
        ]);
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Form\BlogType;
use App\Repository\BlogRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/blog")
 */
class BlogController extends AbstractController
{
    /**
     * @Route("/", name="blog_index", methods={"GET"})
     */
    public function index(BlogRepository $blogRepository): Response
    {
        return $this->render('blog/index.html.twig', [
            'blogs' => $blogRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="blog_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $blog = new Blog();
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($blog);
            $entityManager->flush();

            return $this->redirectToRoute('blog_index');
        }

        return $this->render('blog/new.html.twig', [
            'blog' => $blog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="blog_show", methods={"GET"})
     */
    public function show(Blog $blog): Response
    {
        return $this->render('blog/show.html.twig', [
            'blog' => $blog,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="blog_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Blog $blog): Response
    {
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('blog_index');
        }

        return $this->render('blog/edit.html.twig', [
            'blog' => $blog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="blog_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Blog $blog): Response
    {
        if ($this->isCsrfTokenValid('delete'.$blog->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($blog);
            $entityManager->flush();
        }

        return $this->redirectToRoute('blog_index');
    }
}

templates/blog/_delete_form.html.twig
<form method="post" action="{{ path('blog_delete', {'id': blog.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ blog.id) }}">
    <button class="btn">Delete</button>
</form>

templates/blog/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/blog/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Blog{% endblock %}

{% block body %}
    <h1>Edit Blog</h1>

    {{ include('blog/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('blog_index') }}">back to list</a>

    {{ include('blog/_delete_form.html.twig') }}
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog index{% endblock %}

{% block body %}
    <h1>Blog index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Image</th>
                <th>Date</th>
                <th>Show_home</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for blog in blogs %}
            <tr>
                <td>{{ blog.id }}</td>
                <td>{{ blog.title }}</td>
                <td>{{ blog.description }}</td>
                <td>{{ blog.image }}</td>
                <td>{{ blog.date ? blog.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ blog.showHome ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('blog_show', {'id': blog.id}) }}">show</a>
                    <a href="{{ path('blog_edit', {'id': blog.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('blog_new') }}">Create new</a>
{% endblock %}

templates/blog/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Blog{% endblock %}

{% block body %}
    <h1>Create new Blog</h1>

    {{ include('blog/_form.html.twig') }}

    <a href="{{ path('blog_index') }}">back to list</a>
{% endblock %}

templates/blog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog{% endblock %}

{% block body %}
    <h1>Blog</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ blog.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ blog.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ blog.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ blog.image }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ blog.date ? blog.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Show_home</th>
                <td>{{ blog.showHome ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('blog_index') }}">back to list</a>

    <a href="{{ path('blog_edit', {'id': blog.id}) }}">edit</a>

    {{ include('blog/_delete_form.html.twig') }}
{% endblock %}